---
title: Acoge.me
timezone: UTC
collections:
  dogs:
    title: Dogs
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  sass_dir: _sass
  style: compressed
exclude:
- node_modules
- Gruntfile.js
- package.json
- Gemfile
- Gemfile.lock
