---
title: Acoge.me
timezone: UTC
collections:
  dogs:
    title: Dogs
    output: false
    Need:
    - 
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: global
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: global
lang: en
permalink: pretty
